#ifndef _TYPES_HPP_
#define _TYPES_HPP_

#define ARGUMENT_TYPE_REGISTER  1
#define ARGUMENT_TYPE_ADDR_REG  2
#define ARGUMENT_TYPE_LABEL     3
#define ARGUMENT_TYPE_EXT_REG   4
#define ARGUMENT_TYPE_COND_JUMP 5
#define ARGUMENT_TYPE_ALU_OPER  6

#define DATAARGUMENT_TYPE_DATA    0
#define DATAARGUMENT_TYPE_ADDRESS 1

#define SUBCODES_TYPE_R_TO_R  0
#define SUBCODES_TYPE_R_TO_D  1
#define SUBCODES_TYPE_R_TO_A  2
#define SUBCODES_TYPE_A_TO_R  3
#define SUBCODES_TYPE_R_TO_AR 4
#define SUBCODES_TYPE_AR_TO_R 5
#define SUBCODES_TYPE_AR_TO_D 6


#endif